output: "dharma_test2"


hf_repo: pharaouk/dharma_test3
hf_upload: true
hf_private: false



prompt_format: "Question: {questions}. {options} Answer:"

dataset_size: 100
data_seed: 42
force_dist: true

benchmarks:
  mmlu: 
    count: 1
  arc_c:
    count: 1
  arc_e:
    count: 1
  agieval:
    count: 1
  boolq:
    count: 1
  obqa:
    count: 1
  bigbench:
    count: 0
  truthfulqa:
    count: 1
  winogrande:
    count: 1


